package com.example.key.quiz.database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWER".
*/
public class AnswerDao extends AbstractDao<Answer, Long> {

    public static final String TABLENAME = "ANSWER";

    /**
     * Properties of entity Answer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Answers = new Property(1, String.class, "answers", false, "ANSWERS");
        public final static Property RemoutCommunicationId = new Property(2, long.class, "remoutCommunicationId", false, "REMOUT_COMMUNICATION_ID");
    }

    private DaoSession daoSession;

    private Query<Answer> question_AnswersQuery;

    public AnswerDao(DaoConfig config) {
        super(config);
    }
    
    public AnswerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"ANSWERS\" TEXT NOT NULL ," + // 1: answers
                "\"REMOUT_COMMUNICATION_ID\" INTEGER NOT NULL );"); // 2: remoutCommunicationId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Answer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getAnswers());
        stmt.bindLong(3, entity.getRemoutCommunicationId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Answer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getAnswers());
        stmt.bindLong(3, entity.getRemoutCommunicationId());
    }

    @Override
    protected final void attachEntity(Answer entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Answer readEntity(Cursor cursor, int offset) {
        Answer entity = new Answer( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // answers
            cursor.getLong(offset + 2) // remoutCommunicationId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Answer entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setAnswers(cursor.getString(offset + 1));
        entity.setRemoutCommunicationId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Answer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Answer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Answer entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "answers" to-many relationship of Question. */
    public List<Answer> _queryQuestion_Answers(long remoutCommunicationId) {
        synchronized (this) {
            if (question_AnswersQuery == null) {
                QueryBuilder<Answer> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RemoutCommunicationId.eq(null));
                question_AnswersQuery = queryBuilder.build();
            }
        }
        Query<Answer> query = question_AnswersQuery.forCurrentThread();
        query.setParameter(0, remoutCommunicationId);
        return query.list();
    }

}
