package com.example.key.quiz.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.key.quiz.database.Answer;
import com.example.key.quiz.database.Question;
import com.example.key.quiz.database.UserSuccess;

import com.example.key.quiz.database.AnswerDao;
import com.example.key.quiz.database.QuestionDao;
import com.example.key.quiz.database.UserSuccessDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerDaoConfig;
    private final DaoConfig questionDaoConfig;
    private final DaoConfig userSuccessDaoConfig;

    private final AnswerDao answerDao;
    private final QuestionDao questionDao;
    private final UserSuccessDao userSuccessDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        userSuccessDaoConfig = daoConfigMap.get(UserSuccessDao.class).clone();
        userSuccessDaoConfig.initIdentityScope(type);

        answerDao = new AnswerDao(answerDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);
        userSuccessDao = new UserSuccessDao(userSuccessDaoConfig, this);

        registerDao(Answer.class, answerDao);
        registerDao(Question.class, questionDao);
        registerDao(UserSuccess.class, userSuccessDao);
    }
    
    public void clear() {
        answerDaoConfig.clearIdentityScope();
        questionDaoConfig.clearIdentityScope();
        userSuccessDaoConfig.clearIdentityScope();
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public UserSuccessDao getUserSuccessDao() {
        return userSuccessDao;
    }

}
