package com.example.key.quiz.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.key.quiz.database.Question;
import com.example.key.quiz.database.Repository;

import com.example.key.quiz.database.QuestionDao;
import com.example.key.quiz.database.RepositoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionDaoConfig;
    private final DaoConfig repositoryDaoConfig;

    private final QuestionDao questionDao;
    private final RepositoryDao repositoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        repositoryDaoConfig = daoConfigMap.get(RepositoryDao.class).clone();
        repositoryDaoConfig.initIdentityScope(type);

        questionDao = new QuestionDao(questionDaoConfig, this);
        repositoryDao = new RepositoryDao(repositoryDaoConfig, this);

        registerDao(Question.class, questionDao);
        registerDao(Repository.class, repositoryDao);
    }
    
    public void clear() {
        questionDaoConfig.clearIdentityScope();
        repositoryDaoConfig.clearIdentityScope();
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public RepositoryDao getRepositoryDao() {
        return repositoryDao;
    }

}
